FROM node:22-alpine

WORKDIR /app

RUN mkdir ../config
RUN npm install -g pnpm@latest-10

COPY admin-panel/package.json admin-panel/pnpm-lock.yaml ./

RUN pnpm install

COPY admin-panel .
COPY ./config/proxy.config.json ../config/proxy.config.json

RUN pnpm run build

EXPOSE 4173

CMD ["pnpm", "run", "preview"]