FROM "node:22-alpine"

WORKDIR /app

COPY admin-panel .

RUN mkdir ../.config

COPY ./.config ../.config

RUN npm install -g pnpm@latest-10

RUN pnpm install
RUN pnpm run build

EXPOSE 4173

CMD ["pnpm", "run", "preview"]