FROM golang:1.25.5

WORKDIR /mixproxy

RUN mkdir src
RUN mkdir .config
RUN mkdir certs

COPY ./.config ./.config
COPY ./certs ./certs
COPY ./src ./src
COPY main.go .
COPY go.mod .
COPY go.sum .

RUN go mod download
RUN ls
RUN go build

EXPOSE 80
EXPOSE 443

CMD ["./mixproxy", "--start-proxy"]